In [ ]:
3 + 7

In [ ]:
print("hello")

In [ ]:
name = "Den"
age = 25

In [ ]:
print(age)

In [ ]:
# This is a comment it will not run
# You can echo values without using print in the notebook
name

# Variables and Values

In [ ]:
# variables can be used in calculations
print(age)
age = age + 3
print(age)

In [ ]:
# Order of operations matters!
first = 1
second = first* 5
first = 2 

print (first)
print (second)

In [ ]:
# Values have types. Types affect what you can do with them.
print(5-3)
#print("hello" - "h")

In [ ]:
print(len("hello"))
#print(len(6))

In [ ]:
# Add hashtag in front of code to disable it from running but keeps it on record. kernal tab and restart to rerun cells to retry. 

In [ ]:
## Challenge
Explain what each operator does

print(5 // 3)

print(5 / 3)

print(5 % 3)

In [ ]:
print(5 // 3)

In [ ]:
print(5 / 3)

In [ ]:
print(5 % 3)

In [ ]:
print(7 // 3)

In [ ]:
print(7 / 3)

In [ ]:
# // - floor operator, / - division, % - remainder= this is good for keeping track 

# Getting Help 

In [ ]:
# Rounding Numbers is built in
round(3.14159, 2)

In [ ]:
help(round)

In [ ]:
round(3.14159, ndigits=2)

In [ ]:
# All functions return a new value
rounded_pi = round(3.14159, 2)
print(rounded_pi)

In [ ]:
# making titles and sections is changing the line to markdown and then starting the line with a hastag.

In [ ]:
## Challenge

In what order do the operations happen?

radiance=1.0

radiance=max(2.1,2.0+min(radiance,1.1*radiance-0.5))

In [ ]:
radiance=1.0
radiance=max(2.1,2.0+min(radiance,1.1*radiance-0.5))

In [ ]:
help(min)

In [ ]:
help(max)

In [ ]:
print(radiance)

In [ ]:
# first thing radiance is equal to one. second thing (functions work inside out) 

In [ ]:
# breakdown of operations
radiance = 1.0

min_arg_2 = 1.1 * radiance - 0.5
print("Min arg 2:", min_arg_2)

min_result = min(radiance, min_arg_2)
print("min result:", min_result)

radiance = max(2.1,2.0 + min_result)
print(radiance)

# A Breif Interlude with Git

# Libraries

In [ ]:
import math

In [ ]:
math.pi

In [ ]:
pi

In [ ]:
print(math.pi)
print(math.cos(math.pi)

In [ ]:
print(math.pi)
print(math.cos(math.pi))

In [ ]:
print(math.pi)
print(math.cos(math.pi))

In [ ]:
# get complete help with help()
#help(math)

# Get a list of options with dir()
print(dir(math))

# List

In [ ]:
# a list is an ordered collection of stuff
fruits = ["apple", "Banana", "cherry", "date", "elderberry", "fig"]

In [ ]:
fruits

In [ ]:
len(fruits)

In [ ]:
# Lists are indexed by position, counting, from 0
# First item
print(fruits[0])

# Fifth item
print(fruits[4])

In [ ]:
# Get subsets by slicing the list
# Get the first three items
fruits[0:3]

In [ ]:
fruits[2:5]

In [ ]:
# Get items by step
# Get the first 5 items every other item
fruits[0:5:2]

In [ ]:
# Get first 5 items, every 3rd item
fruits[0:5:3]

In [ ]:
print(len(fruits))

## challenge

What are the following statements doing?

fruits[-1]

fruits[20]

fruits[-3]

In [ ]:
fruits[-1]

fruits[20]

fruits[-3]

In [ ]:
fruits[-1]

In [ ]:
#fruits[20]

In [ ]:
fruits[-3:]

In [ ]:
fruits

In [ ]:
# Why are lists indexed this way?
print(fruits[:2])
print(fruits[2:])
print(len(fruits[1:3]))

# Adding stuff to Lists

In [ ]:
# Update a specific item
print(fruits)

fruits[0] = "apricot"
print(fruits)

In [ ]:
# Add new items to list
fruits.append("grape")

print(fruits)

In [ ]:
# Add items form a second list the the first list
more_fruits = ["honeydew", "imbe", "jackfruit"]
fruits.extend(more_fruits)

print(fruits)

In [ ]:
# Many funnctions operate on collections
# Assesing our wide recieving corp
recieving_yards = [450, 370, 870, 150]

mean_yards = sum(recieving_yards)/len(recieving_yards)
print(mean_yards)

# For Loops

In [ ]:
for fruit in fruits:
    print(fruit)

In [ ]:
for bob in fruits:
    print(bob)

In [ ]:
# Code blocks can contain many statements
primes = [2, 3, 5]
for p in primes:
    squared = p ** 2
    cubed = p ** 3
    print(p, squared, cubed)

In [ ]:
# Create a new collection from a existing collection
primes_squared = []
for p in primes:
    primes_squared.append(p ** 2)

print(primes_squared)

## challenge

Get the total length of all the items int the fruits list.

In [ ]:
print(fruits)

In [ ]:
fruits = ["apricot", "Banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew", "imbe", "jackfruit"]

In [ ]:
print(fruits)

In [ ]:
a = 0

In [ ]:
a += 1

In [ ]:
a

In [ ]:
len("hi")

In [ ]:
a = len("hi")

In [ ]:
a

In [ ]:
f_len = []
for f in fruits:
    f_len.append(len(f))

print(f_len)
sum(f_len)
    

In [ ]:
joined_fruits = "".join(fruits)
print(joined_fruits)
print(len(joined_fruits))

# Linear Algebra with NumPy

In [3]:
import numpy as np

In [5]:
# Create an array for random numbers
m_rand = np.random.rand(3,4)
print(m_rand)

[[0.15893152 0.17092001 0.41523893 0.9700433 ]
 [0.24202673 0.45809989 0.2098739  0.48763835]
 [0.40334465 0.43660765 0.57284943 0.96317153]]


In [7]:
m_rand[0, 0]

0.1589315152296038

In [9]:
m_rand[0, 1]

0.170920012941994

In [11]:
# first number is row, second is column

In [13]:
# Arrays have attributes
print(m_rand.shape)
print(m_rand.size)
print(m_rand.ndim)

(3, 4)
12
2


In [16]:
# Linear algebra
x = np.arange(9)
y = np.arange(9)

print(x)
print(y)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [18]:
# Operations are element-wise by default
x * y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [20]:
# Mtrix-wise operations if you like
x @ y

204

In [22]:
# You can reshape arrays
x1 = x.reshape(3, 3)
x2 = x.reshape(9, 1)

print(x)
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Challenge

1.create a 3 x 3 array containing the number 0-8
2. multiply the array byitself element-wise
3. Multiply the array by its transpose( look up)
4. Divide the array by itself

In [25]:
x = np.arange(9)
print(x)
x1 = x.reshape(3, 3)
print(x1)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
x1 * x1

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [39]:
# Use method chaining to do more work on one line
demo = np.arange(9).reshape(3, 3)
print(demo)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
demo * demo

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [43]:
# get transpose method 1
demo * demo.T

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [45]:
#get transpose, method 2
demo * np.transpose(demo)

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [47]:
demo / demo

C:\Users\denar\AppData\Local\Temp\ipykernel_8684\25692003.py:1: RuntimeWarning: invalid value encountered in divide
  demo / demo


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# Working wtih data in Pandas

In [52]:
import pandas as pd

In [54]:
data = pd.read_csv("gapminder_gdp_oceania.csv")
print(data)

       country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686   
1  New Zealand     10556.57566     12247.39532     13175.67800   

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928   
1     14463.91893     16046.03728     16233.71770     17632.41040   

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473   
1     19007.19129     18363.32494     21050.41377     23189.80135   

   gdpPercap_2007  
0     34435.36744  
1     25185.00911  


In [56]:
data

country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686   
1  New Zealand     10556.57566     12247.39532     13175.67800   

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928   
1     14463.91893     16046.03728     16233.71770     17632.41040   

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473   
1     19007.19129     18363.32494     21050.41377     23189.80135   

   gdpPercap_2007  
0     34435.36744  
1     25185.00911

In [58]:
# Import csv and index by country name
data = pd.read_csv("gapminder_gdp_oceania.csv", index_col ="country")

In [60]:
data

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                       
Australia       10039.59564     10949.64959     12217.22686     14526.12465   
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893   

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                       
Australia       16788.62948     18334.19751     19477.00928     21888.88903   
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129   

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                      
Australia       23424.76683     26997.93657     30687.75473     34435.36744  
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911

In [62]:
# Good advice about Python
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [64]:
# data frames have attributes
print(data.index)
print(data.columns)
print(data.shape)

Index(['Australia', 'New Zealand'], dtype='object', name='country')
Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')
(2, 12)


In [66]:
# data frames can tell you about their contents
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gdpPercap_1952  2 non-null      float64
 1   gdpPercap_1957  2 non-null      float64
 2   gdpPercap_1962  2 non-null      float64
 3   gdpPercap_1967  2 non-null      float64
 4   gdpPercap_1972  2 non-null      float64
 5   gdpPercap_1977  2 non-null      float64
 6   gdpPercap_1982  2 non-null      float64
 7   gdpPercap_1987  2 non-null      float64
 8   gdpPercap_1992  2 non-null      float64
 9   gdpPercap_1997  2 non-null      float64
 10  gdpPercap_2002  2 non-null      float64
 11  gdpPercap_2007  2 non-null      float64
dtypes: float64(12)
memory usage: 208.0+ bytes


In [68]:
# get descriptive statistics
data.describe()

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
count        2.000000        2.000000        2.000000        2.000000   
mean     10298.085650    11598.522455    12696.452430    14495.021790   
std        365.560078      917.644806      677.727301       43.986086   
min      10039.595640    10949.649590    12217.226860    14463.918930   
25%      10168.840645    11274.086022    12456.839645    14479.470360   
50%      10298.085650    11598.522455    12696.452430    14495.021790   
75%      10427.330655    11922.958888    12936.065215    14510.573220   
max      10556.575660    12247.395320    13175.678000    14526.124650   

       gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
count         2.00000        2.000000        2.000000        2.000000   
mean      16417.33338    17283.957605    18554.709840    20448.040160   
std         525.09198     1485.263517     1304.328377     2037.668013   
min       16046.03728    16233.717700    17632.410400    19007.191290   
25%       16231.68533    16758.837652    18093.560120    19727.615725   
50%       16417.33338    17283.957605    18554.709840    20448.040160   
75%       16602.98143    17809.077558    19015.859560    21168.464595   
max       16788.62948    18334.197510    19477.009280    21888.889030   

       gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
count        2.000000        2.000000        2.000000        2.000000  
mean     20894.045885    24024.175170    26938.778040    29810.188275  
std       3578.979883     4205.533703     5301.853680     6540.991104  
min      18363.324940    21050.413770    23189.801350    25185.009110  
25%      19628.685412    22537.294470    25064.289695    27497.598692  
50%      20894.045885    24024.175170    26938.778040    29810.188275  
75%      22159.406358    25511.055870    28813.266385    32122.777858  
max      23424.766830    26997.936570    30687.754730    34435.367440

In [72]:
# Get the first n rows
data.head(1)

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                     
Australia     10039.59564     10949.64959     12217.22686     14526.12465   

           gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                     
Australia     16788.62948     18334.19751     19477.00928     21888.88903   

           gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                    
Australia     23424.76683     26997.93657     30687.75473     34435.36744

# Subsetting Data

In [75]:
data = pd.read_csv("gapminder_gdp_europe.csv", index_col = "country")

In [79]:
data.head(3)

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                   
Albania     1601.056136     1942.284244     2312.888958     2760.196931   
Austria     6137.076492     8842.598030    10750.721110    12834.602400   
Belgium     8343.105127     9714.960623    10991.206760    13149.041190   

         gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                   
Albania     3313.422188      3533.00391     3630.880722     3738.932735   
Austria    16661.625600     19749.42230    21597.083620    23687.826070   
Belgium    16672.143560     19117.97448    20979.845890    22525.563080   

         gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                  
Albania     2497.437901     3193.054604     4604.211737     5937.029526  
Austria    27042.018680    29095.920660    32417.607690    36126.492700  
Belgium    25575.570690    27561.196630    30485.883750    33692.605080

In [83]:
#get item by index location
data.iloc[0,0]

1601.056136

In [85]:
# get item by label
data.loc["Albania","gdpPercap_1952"]

1601.056136

# A brief digression on string methods

In [88]:
# standard python has string methods.
big_hello = "hello".title()
print(big_hello)

Hello


In [90]:
help("hello".title)

Help on built-in function title:

title() method of builtins.str instance
    Return a version of the string where each word is titlecased.

    More specifically, words start with uppercased characters and all remaining
    cased characters have lower case.



In [92]:
# What methods are avaialable?
print(dir("hello"))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [94]:
print(data.columns)

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')


In [96]:
print(dir(data.columns.str))

['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__frozen', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', '_doc_args', '_freeze', '_get_series_list', '_index', '_inferred_dtype', '_is_categorical', '_is_string', '_name', '_orig', '_parent', '_validate', '_wrap_result', 'capitalize', 'casefold', 'cat', 'center', 'contains', 'count', 'decode', 'encode', 'endswith', 'extract', 'extractall', 'find', 'findall', 'fullmatch', 'get', 'get_dummies', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'len', 'ljust', 'lower', 'lstrip', 'match', 'normalize', 'pad', 'partition', 'removeprefix', 'removesuffix', 'rep

In [98]:
# rewrite column headers tp strip offf leading text
data.columns = data.columns.str.strip("gdpPercap_")
print(data.columns)

Index(['1952', '1957', '1962', '1967', '1972', '1977', '1982', '1987', '1992',
       '1997', '2002', '2007'],
      dtype='object')


In [104]:
data.loc["Albania", "1952"]

1601.056136

In [124]:
data.loc["Italy":"Poland", "1962":"1972"]
subset = data.loc["Italy":"Poland", "1962":"1972"]

In [118]:
data.loc["Italy":"Poland", :]

1952          1957          1962          1967  \
country                                                               
Italy         4931.404155   6248.656232   8243.582340  10022.401310   
Montenegro    2647.585601   3682.259903   4649.593785   5907.850937   
Netherlands   8941.571858  11276.193440  12790.849560  15363.251360   
Norway       10095.421720  11653.973040  13450.401510  16361.876470   
Poland        4029.329699   4734.253019   5338.752143   6557.152776   

                     1972          1977          1982          1987  \
country                                                               
Italy        12269.273780  14255.984750  16537.483500  19207.234820   
Montenegro    7778.414017   9595.929905  11222.587620  11732.510170   
Netherlands  18794.745670  21209.059200  21399.460460  23651.323610   
Norway       18965.055510  23311.349390  26298.635310  31540.974800   
Poland        8006.506993   9508.141454   8451.531004   9082.351172   

                     1992          1997          2002          2007  
country                                                              
Italy        22013.644860  24675.024460  27968.098170  28569.719700  
Montenegro    7003.339037   6465.613349   6557.194282   9253.896111  
Netherlands  26790.949610  30246.130630  33724.757780  36797.933320  
Norway       33965.661150  41283.164330  44683.975250  49357.190170  
Poland        7738.881247  10159.583680  12002.239080  15389.924680

In [126]:
subset

1962          1967          1972
country                                              
Italy         8243.582340  10022.401310  12269.273780
Montenegro    4649.593785   5907.850937   7778.414017
Netherlands  12790.849560  15363.251360  18794.745670
Norway       13450.401510  16361.876470  18965.055510
Poland        5338.752143   6557.152776   8006.506993

In [128]:
subset.describe()

1962          1967          1972
count      5.000000      5.000000      5.000000
mean    8894.635868  10842.506571  13162.799194
std     4093.410673   4855.106424   5517.298708
min     4649.593785   5907.850937   7778.414017
25%     5338.752143   6557.152776   8006.506993
50%     8243.582340  10022.401310  12269.273780
75%    12790.849560  15363.251360  18794.745670
max    13450.401510  16361.876470  18965.055510

In [130]:
subset.max()

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64

## Challenge

1. calculate subset.max() and assign the results to a variable. WHat kind of thing is it?
2. what is the maximum vaule of the new thing?
3. Can you calculate the overall max value of the subset in the 1 step?
   

In [133]:
subset.max()

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64

In [135]:
subset_max =subset.max()
print(subset_max)

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64


In [137]:
print(type(subset))
print(type(subset_max))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [139]:
subset_max.max()

18965.05551

In [141]:
# Solution 1
subset.max().max()

18965.05551

In [143]:
# Solution 2 
print("Default max")
print(subset.max())
print("Max along axis 0")
print(subset.max(axis = 0))
print("Max along axis 1")
print(subset.max(axis = 1))

Default max
1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64
Max along axis 0
1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64
Max along axis 1
country
Italy          12269.273780
Montenegro      7778.414017
Netherlands    18794.745670
Norway         18965.055510
Poland          8006.506993
dtype: float64


In [145]:
# get for overall data frame
subset.max(axis = None)

18965.05551

# Filter data by criteria


In [148]:
subset

1962          1967          1972
country                                              
Italy         8243.582340  10022.401310  12269.273780
Montenegro    4649.593785   5907.850937   7778.414017
Netherlands  12790.849560  15363.251360  18794.745670
Norway       13450.401510  16361.876470  18965.055510
Poland        5338.752143   6557.152776   8006.506993

In [150]:
# get gdps greater than 100000
subset > 10000

1962   1967   1972
country                         
Italy        False   True   True
Montenegro   False  False  False
Netherlands   True   True   True
Norway        True   True   True
Poland       False  False  False

In [152]:
# Filter the data frame by the criterion
df = subset[subset > 10000]
df

1962         1967         1972
country                                           
Italy                NaN  10022.40131  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

In [158]:
# get everything above the median
subset[subset > subset.median(axis = None)]

1962         1967         1972
country                                           
Italy                NaN          NaN  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

# Working with missing data

In [164]:
# Missing data is ignored by default
print("Column means")
print(df.mean())

print("Row means")
print(df.mean(axis = 1))


Column means
1962    13120.625535
1967    13915.843047
1972    16676.358320
dtype: float64
Row means
country
Italy          11145.837545
Montenegro              NaN
Netherlands    15649.615530
Norway         16259.111163
Poland                  NaN
dtype: float64


In [166]:
# Check for missing values
df.isna()

1962   1967   1972
country                         
Italy         True  False  False
Montenegro    True   True   True
Netherlands  False  False  False
Norway       False  False  False
Poland        True   True   True

In [168]:
# Count our missing values
# Missing by row
df.isna().sum()

1962    3
1967    2
1972    2
dtype: int64

In [170]:
# check total missing valuese
df.isna().sum().sum()

7

In [172]:
# Drop missing values
df.dropna()

1962         1967         1972
country                                           
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551

In [176]:
# Replace missing values with a fixed value
df_fixed = df.fillna(99)
print(df_fixed)

                    1962         1967         1972
country                                           
Italy           99.00000  10022.40131  12269.27378
Montenegro      99.00000     99.00000     99.00000
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland          99.00000     99.00000     99.00000


In [180]:
# Replace missing values with interpolated data
df_interpolated  = df.interpolate()
print(df_interpolated)

                    1962          1967          1972
country                                             
Italy                NaN  10022.401310  12269.273780
Montenegro           NaN  12692.826335  15532.009725
Netherlands  12790.84956  15363.251360  18794.745670
Norway       13450.40151  16361.876470  18965.055510
Poland       13450.40151  16361.876470  18965.055510


## Challenge :the perils of missing data
1. create an array of random numbers matching the "data" data frame

random_filter = np.random.rand(30,12) * data.max(axis = None)

2. Create a new data frame that filters out all values lower than the random numbers
4. Interpolate the new values for the missing data in the new data frame. How accurate are they?

In [183]:
random_filter = np.random.rand(30,12) * data.max(axis = None)

In [186]:
random_filter

array([[16026.70525325, 16784.89908248, 36357.48952953, 13057.16450338,
        34300.43535111,  9838.56961969,  5271.9234613 , 45908.03966032,
         1784.72566711, 13263.26471048, 29017.03047545, 27305.36260398],
       [24675.96728687,  7857.51137907,  5860.33028367, 30611.7338307 ,
        26870.40607483, 40941.10386218, 40083.07610565, 30402.59177668,
         8581.68728483,  7534.92905544, 42299.80309685, 12477.64393282],
       [48261.507966  ,  1641.7865759 , 22071.46898484, 47087.89029853,
        20170.62553059, 31561.8880384 , 15213.62999217,  1208.14541568,
        24332.22788436, 27675.34991764, 36763.71477211, 26394.82483615],
       [27945.54087368, 42116.14219287, 15511.8871393 , 44479.14212751,
        19897.89210837, 23297.53340092, 32062.71469761, 42348.1736347 ,
        48334.79035794, 34709.12267145,  7782.34370837, 23486.32976102],
       [46020.33328344, 23549.69747151, 37355.8524552 , 15156.20613039,
        46130.98893214, 43917.60294549, 24078.01424707, 4926

In [194]:
data > random_filter

1952   1957   1962   1967   1972   1977   1982  \
country                                                                   
Albania                 False  False  False  False  False  False  False   
Austria                 False   True   True  False  False  False  False   
Belgium                 False   True  False  False  False  False   True   
Bosnia and Herzegovina  False  False  False  False  False  False  False   
Bulgaria                False  False  False  False  False  False  False   
Croatia                 False  False  False  False  False  False  False   
Czech Republic          False  False  False  False  False  False  False   
Denmark                 False  False  False   True  False  False  False   
Finland                 False  False  False  False  False   True  False   
France                  False  False  False   True   True  False  False   
Germany                 False  False  False  False  False   True   True   
Greece                  False  False   True  False   True  False  False   
Hungary                 False  False  False  False  False  False   True   
Iceland                 False  False  False  False  False   True  False   
Ireland                 False  False  False   True  False  False  False   
Italy                   False  False  False   True  False   True   True   
Montenegro              False  False  False   True  False   True  False   
Netherlands             False  False   True  False   True   True   True   
Norway                  False  False  False  False  False  False   True   
Poland                  False  False   True   True   True   True  False   
Portugal                False  False  False  False  False  False  False   
Romania                 False  False  False  False  False  False   True   
Serbia                  False  False   True  False  False  False  False   
Slovak Republic         False  False  False  False  False  False  False   
Slovenia                False  False   True  False  False  False  False   
Spain                   False  False  False  False  False  False  False   
Sweden                  False  False  False   True  False  False  False   
Switzerland              True  False   True   True  False  False   True   
Turkey                  False  False  False  False  False  False  False   
United Kingdom           True  False  False  False  False  False  False   

                         1987   1992   1997   2002   2007  
country                                                    
Albania                 False   True  False  False  False  
Austria                 False   True   True  False   True  
Belgium                  True   True  False  False   True  
Bosnia and Herzegovina  False  False  False  False  False  
Bulgaria                False  False  False  False  False  
Croatia                 False  False  False  False  False  
Czech Republic           True   True  False  False  False  
Denmark                 False  False   True  False   True  
Finland                  True   True  False  False  False  
France                  False  False  False   True   True  
Germany                  True  False   True  False   True  
Greece                  False  False  False   True   True  
Hungary                  True  False  False   True   True  
Iceland                 False   True   True   True   True  
Ireland                 False   True  False   True   True  
Italy                   False  False  False  False   True  
Montenegro              False  False  False  False   True  
Netherlands             False  False   True   True   True  
Norway                   True   True  False   True   True  
Poland                   True  False  False  False   True  
Portugal                 True  False   True  False  False  
Romania                 False  False  False   True   True  
Serbia                   True  False  False  False   True  
Slovak Republic         False   True  False  False  False  
Slovenia                 True   True  False   True  False  
Spai

In [198]:
rf = data[data > random_filter]
rf

1952         1957          1962          1967  \
country                                                                         
Albania                          NaN          NaN           NaN           NaN   
Austria                          NaN  8842.598030  10750.721110           NaN   
Belgium                          NaN  9714.960623           NaN           NaN   
Bosnia and Herzegovina           NaN          NaN           NaN           NaN   
Bulgaria                         NaN          NaN           NaN           NaN   
Croatia                          NaN          NaN           NaN           NaN   
Czech Republic                   NaN          NaN           NaN           NaN   
Denmark                          NaN          NaN           NaN  15937.211230   
Finland                          NaN          NaN           NaN           NaN   
France                           NaN          NaN           NaN  12999.917660   
Germany                          NaN          NaN           NaN           NaN   
Greece                           NaN          NaN   6017.190733           NaN   
Hungary                          NaN          NaN           NaN           NaN   
Iceland                          NaN          NaN           NaN           NaN   
Ireland                          NaN          NaN           NaN   7655.568963   
Italy                            NaN          NaN           NaN  10022.401310   
Montenegro                       NaN          NaN           NaN   5907.850937   
Netherlands                      NaN          NaN  12790.849560           NaN   
Norway                           NaN          NaN           NaN           NaN   
Poland                           NaN          NaN   5338.752143   6557.152776   
Portugal                         NaN          NaN           NaN           NaN   
Romania                          NaN          NaN           NaN           NaN   
Serbia                           NaN          NaN   6289.629157           NaN   
Slovak Republic                  NaN          NaN           NaN           NaN   
Slovenia                         NaN          NaN   7402.303395           NaN   
Spain                            NaN          NaN           NaN           NaN   
Sweden                           NaN          NaN           NaN  15258.296970   
Switzerland             14734.232750          NaN  20431.092700  22966.144320   
Turkey                           NaN          NaN           NaN           NaN   
United Kingdom           9979.508487          NaN           NaN           NaN   

                                1972          1977          1982  \
country                                                            
Albania                          NaN           NaN           NaN   
Austria                          NaN           NaN           NaN   
Belgium                          NaN           NaN  20979.845890   
Bosnia and Herzegovina           NaN           NaN           NaN   
Bulgaria                         NaN           NaN           NaN   
Croatia                          NaN           NaN           NaN   
Czech Republic                   NaN           NaN           NaN   
Denmark                          NaN           NaN           NaN   
Finland                          NaN  15605.422830           NaN   
France                  16107.191710           NaN           NaN   
Germany                          NaN  20512.921230  22031.532740   
Greece                  12724.829570           NaN           NaN   
Hungary                          NaN           NaN  12545.990660   
Iceland                          NaN  19654.962470           NaN   
Ireland                          NaN           NaN           NaN   
Italy                            NaN  14255.984750  16537.483500   
Montenegro                       NaN   9595.929905           NaN   
Netherlands             18794.745670  21209.059200  21399.460460   
Norway                           NaN           NaN  26298.635310   
Poland     

In [204]:
rf.interpolate()

1952         1957          1962          1967  \
country                                                                         
Albania                          NaN          NaN           NaN           NaN   
Austria                          NaN  8842.598030  10750.721110           NaN   
Belgium                          NaN  9714.960623  10277.368072           NaN   
Bosnia and Herzegovina           NaN  9714.960623   9804.015035           NaN   
Bulgaria                         NaN  9714.960623   9330.661997           NaN   
Croatia                          NaN  9714.960623   8857.308959           NaN   
Czech Republic                   NaN  9714.960623   8383.955922           NaN   
Denmark                          NaN  9714.960623   7910.602884  15937.211230   
Finland                          NaN  9714.960623   7437.249846  14468.564445   
France                           NaN  9714.960623   6963.896808  12999.917660   
Germany                          NaN  9714.960623   6490.543771  11931.047921   
Greece                           NaN  9714.960623   6017.190733  10862.178181   
Hungary                          NaN  9714.960623   7146.133871   9793.308442   
Iceland                          NaN  9714.960623   8275.077009   8724.438702   
Ireland                          NaN  9714.960623   9404.020147   7655.568963   
Italy                            NaN  9714.960623  10532.963284  10022.401310   
Montenegro                       NaN  9714.960623  11661.906422   5907.850937   
Netherlands                      NaN  9714.960623  12790.849560   6124.284883   
Norway                           NaN  9714.960623   9064.800852   6340.718830   
Poland                           NaN  9714.960623   5338.752143   6557.152776   
Portugal                         NaN  9714.960623   5655.711148   7800.173375   
Romania                          NaN  9714.960623   5972.670152   9043.193974   
Serbia                           NaN  9714.960623   6289.629157  10286.214573   
Slovak Republic                  NaN  9714.960623   6845.966276  11529.235173   
Slovenia                         NaN  9714.960623   7402.303395  12772.255772   
Spain                            NaN  9714.960623  11745.233163  14015.276371   
Sweden                           NaN  9714.960623  16088.162932  15258.296970   
Switzerland             14734.232750  9714.960623  20431.092700  22966.144320   
Turkey                  12356.870618  9714.960623  20431.092700  22966.144320   
United Kingdom           9979.508487  9714.960623  20431.092700  22966.144320   

                                1972          1977          1982  \
country                                                            
Albania                          NaN           NaN           NaN   
Austria                          NaN           NaN           NaN   
Belgium                          NaN           NaN  20979.845890   
Bosnia and Herzegovina           NaN           NaN  21111.306746   
Bulgaria                         NaN           NaN  21242.767603   
Croatia                          NaN           NaN  21374.228459   
Czech Republic                   NaN           NaN  21505.689315   
Denmark                          NaN           NaN  21637.150171   
Finland                          NaN  15605.422830  21768.611027   
France                  16107.191710  18059.172030  21900.071884   
Germany                 14416.010640  20512.921230  22031.532740   
Greece                  12724.829570  20226.934977  17288.761700   
Hungary                 13736.482253  19940.948723  12545.990660   
Iceland                 14748.134937  19654.962470  13876.488273   
Ireland                 15759.787620  16955.473610  15206.985887   
Italy                   16771.440303  14255.984750  16537.483500   
Montenegro              17783.092987   9595.929905  18968.471980   
Netherlands             18794.745670  21209.059200  21399.460460   
Norway                  13400.626331  15358.600327  26298.635310   
Poland     

In [210]:
rf_interpolated = rf.interpolate()

In [208]:
data.describe()

1952          1957          1962          1967          1972  \
count     30.000000     30.000000     30.000000     30.000000     30.000000   
mean    5661.057435   6963.012816   8365.486814  10143.823757  12479.575246   
std     3114.060493   3677.950146   4199.193906   4724.983889   5509.691411   
min      973.533195   1353.989176   1709.683679   2172.352423   2860.169750   
25%     3241.132406   4394.874315   5373.536612   6657.939047   9057.708094   
50%     5142.469716   6066.721495   7515.733737   9366.067033  12326.379990   
75%     7236.794919   9597.220820  10931.085348  13277.182058  16523.017127   
max    14734.232750  17909.489730  20431.092700  22966.144320  27195.113040   

               1977          1982          1987          1992          1997  \
count     30.000000     30.000000     30.000000     30.000000     30.000000   
mean   14283.979110  15617.896551  17214.310727  17061.568084  19076.781802   
std     5874.464896   6453.234827   7482.957960   9109.804361  10065.457716   
min     3528.481305   3630.880722   3738.932735   2497.437901   3193.054604   
25%    10360.030300  11449.870115  12274.570680   8667.113214   9946.599306   
50%    14225.754515  15322.824720  16215.485895  17550.155945  19596.498550   
75%    19052.412163  20901.729730  23321.587723  25034.243045  27189.530312   
max    26982.290520  28397.715120  31540.974800  33965.661150  41283.164330   

               2002          2007  
count     30.000000     30.000000  
mean   21711.732422  25054.481636  
std    11197.355517  11800.339811  
min     4604.211737   5937.029526  
25%    11721.851483  14811.898210  
50%    23674.863230  28054.065790  
75%    30373.363307  33817.962533  
max    44683.975250  49357.190170

In [214]:
rf_interpolated.describe()

1952         1957          1962          1967          1972  \
count      3.000000    29.000000     29.000000     23.000000     21.000000   
mean   12356.870618  9684.879154   9921.757681  12040.335802  11538.758045   
std     2377.362132   161.993667   4351.512205   5227.177586   4020.177120   
min     9979.508487  8842.598030   5338.752143   5907.850937   8006.506993   
25%    11168.189553  9714.960623   6963.896808   8262.306039   8006.506993   
50%    12356.870618  9714.960623   8857.308959  10862.178181   8006.506993   
75%    13545.551684  9714.960623  10750.721110  14241.920408  14748.134937   
max    14734.232750  9714.960623  20431.092700  22966.144320  18794.745670   

               1977          1982          1987          1992          1997  \
count     22.000000     28.000000     28.000000     30.000000     29.000000   
mean   13452.953002  20049.409404  20613.545710  22068.743635  25416.498458   
std     4705.083905   4891.444685   5843.557264   7013.344971   4588.914614   
min     9508.141454   9605.314053   9082.351172   2497.437901  17641.031560   
25%     9508.141454  16370.474560  16252.556496  17930.953367  20445.298960   
50%     9552.035680  21177.037174  19294.657413  22600.994560  27970.361160   
75%    17783.247425  21932.937098  23427.304310  25715.571435  29213.991495   
max    21209.059200  28397.715120  31540.974800  33965.661150  30246.130630   

               2002          2007  
count     21.000000     29.000000  
mean   26866.484022  28781.779910  
std     8962.437517  10302.513892  
min     7885.360081   9253.896111  
25%    20660.019360  20874.488456  
50%    29478.999190  32874.217720  
75%    33724.757780  35278.418740  
max    44683.975250  49357.190170

# Sorting and grouping

In [217]:
# Z score all of the GDP data points
z =(data - data.mean(axis = None))/data.values.std(ddof=1)

In [219]:
z

1952      1957      1962      1967      1972  \
country                                                                    
Albania                -1.375535 -1.339060 -1.299445 -1.251631 -1.192496   
Austria                -0.890669 -0.601470 -0.397506 -0.174755  0.234324   
Belgium                -0.654862 -0.508221 -0.371800 -0.141144  0.235448   
Bosnia and Herzegovina -1.442612 -1.401944 -1.363923 -1.314467 -1.240945   
Bulgaria               -1.285400 -1.225071 -1.091919 -0.950537 -0.841454   
Croatia                -1.213253 -1.082952 -0.961131 -0.802673 -0.567105   
Czech Republic         -0.811669 -0.664136 -0.463122 -0.328163 -0.145483   
Denmark                -0.510634 -0.360207 -0.094724  0.156890  0.469977   
Finland                -0.859944 -0.740129 -0.544898 -0.379237 -0.011822   
France                 -0.795243 -0.620685 -0.417841 -0.157084  0.175059   
Germany                -0.783024 -0.457675 -0.167502  0.029518  0.379115   
Greece                 -1.169272 -1.021161 -0.903484 -0.636691 -0.186489   
Hungary                -0.984029 -0.901027 -0.739600 -0.549729 -0.459724   
Iceland                -0.769815 -0.558563 -0.440323 -0.122881  0.142016   
Ireland                -0.989736 -0.948177 -0.837809 -0.728354 -0.527909   
Italy                  -1.019546 -0.878742 -0.665500 -0.475358 -0.235185   
Montenegro             -1.263669 -1.153070 -1.049669 -0.915171 -0.715223   
Netherlands            -0.590890 -0.341337 -0.179432  0.095538  0.462338   
Norway                 -0.467553 -0.300955 -0.108931  0.202283  0.480543   
Poland                 -1.115971 -1.040620 -0.976004 -0.845766 -0.690841   
Portugal               -1.218695 -1.143203 -1.041293 -0.866678 -0.582267   
Romania                -1.210540 -1.125159 -1.040540 -0.854989 -0.690317   
Serbia                 -1.163845 -1.014235 -0.874362 -0.692423 -0.421947   
Slovak Republic        -1.004233 -0.895352 -0.747003 -0.647401 -0.512581   
Slovenia               -1.096120 -0.920043 -0.755426 -0.541301 -0.222976   
Spain                  -1.136846 -1.058733 -0.938047 -0.692230 -0.409475   
Sweden                 -0.635114 -0.487172 -0.228753  0.084319  0.359431   
Switzerland             0.028300  0.367711  0.637251  0.908228  1.360272   
Turkey                 -1.336193 -1.309507 -1.298378 -1.244559 -1.177822   
United Kingdom         -0.479943 -0.340591 -0.212961 -0.034914  0.152390   

                            1977      1982      1987      1992      1997  \
country                                                                    
Albania                -1.169024 -1.158562 -1.147012 -1.279718 -1.205362   
Austria                 0.564385  0.761886  0.985370  1.343908  1.563454   
Belgium                 0.496889  0.695908  0.861133  1.187156  1.399404   
Bosnia and Herzegovina -1.169508 -1.105572 -1.085530 -1.274444 -1.037188   
Bulgaria               -0.732985 -0.667573 -0.665898 -0.872973 -0.908487   
Croatia                -0.338217 -0.133365 -0.069148 -0.643671 -0.491049   
Czech Republic          0.035348  0.097032  0.196785 -0.018434  0.168787   
Denmark                 0.636375  0.771609  1.138050  1.276001  1.639179   
Finland                 0.121424  0.434376  0.713136  0.660347  0.989232   
France                  0.408666  0.622586  0.812057  1.093970  1.220743   
Germany                 0.645998  0.808325  1.087063  1.286537  1.423742   
Greece                 -0.029283  0.085401  0.176485  0.328375  0.457309   
Hungary                -0.298725 -0.205606 -0.158521 -0.420498 -0.294670   
Iceland                 0.554288  0.940666  1.331208  1.141066  1.452840   
Ireland                -0.354721 -0.197874 -0.063773  0.330227  1.074532   
Italy                  -0.022821  0.221054  0.506430  0.806413  1.090894   
Montenegro             -0.520944 -0.347067 -0.292560 -0.798072 -0.855551   
Netherlands             0.720409  0.740762  0.981469  1.317070  1.686402   
Norway                  0.945128  1.264446  1.824811  2.083992  2.866176   

In [223]:
# get mean z scpre fpr each country
mean_z = z.mean(axis=1)
mean_z.sort_values()

country
Albania                  -1.198702
Bosnia and Herzegovina   -1.174179
Turkey                   -1.068925
Bulgaria                 -0.864269
Montenegro               -0.776189
Romania                  -0.766343
Poland                   -0.647011
Serbia                   -0.552037
Croatia                  -0.549187
Slovak Republic          -0.433335
Hungary                  -0.382813
Portugal                 -0.333010
Czech Republic           -0.058733
Greece                   -0.053493
Spain                    -0.046995
Slovenia                 -0.042211
Ireland                   0.137798
Italy                     0.189812
Finland                   0.321131
France                    0.466488
United Kingdom            0.524948
Belgium                   0.580562
Sweden                    0.585091
Austria                   0.635201
Iceland                   0.647975
Germany                   0.650676
Denmark                   0.769875
Netherlands               0.778109
Norway      

In [225]:
bool_z = mean_z > 0
bool_z

country
Albania                   False
Austria                    True
Belgium                    True
Bosnia and Herzegovina    False
Bulgaria                  False
Croatia                   False
Czech Republic            False
Denmark                    True
Finland                    True
France                     True
Germany                    True
Greece                    False
Hungary                   False
Iceland                    True
Ireland                    True
Italy                      True
Montenegro                False
Netherlands                True
Norway                     True
Poland                    False
Portugal                  False
Romania                   False
Serbia                    False
Slovak Republic           False
Slovenia                  False
Spain                     False
Sweden                     True
Switzerland                True
Turkey                    False
United Kingdom             True
dtype: bool

In [227]:
# add new columns to data frame
data["mean_Z"] = mean_z
data["wealthy"] = bool_z

In [229]:
data.head(3)

1952         1957          1962          1967          1972  \
country                                                                       
Albania  1601.056136  1942.284244   2312.888958   2760.196931   3313.422188   
Austria  6137.076492  8842.598030  10750.721110  12834.602400  16661.625600   
Belgium  8343.105127  9714.960623  10991.206760  13149.041190  16672.143560   

                1977          1982          1987          1992          1997  \
country                                                                        
Albania   3533.00391   3630.880722   3738.932735   2497.437901   3193.054604   
Austria  19749.42230  21597.083620  23687.826070  27042.018680  29095.920660   
Belgium  19117.97448  20979.845890  22525.563080  25575.570690  27561.196630   

                 2002          2007    mean_Z  wealthy  
country                                                 
Albania   4604.211737   5937.029526 -1.198702    False  
Austria  32417.607690  36126.492700  0.635201     True  
Belgium  30485.883750  33692.605080  0.580562     True

In [235]:
# get descriptive stats for groups
data.groupby("wealthy").mean()

1952         1957          1962          1967          1972  \
wealthy                                                                       
False    3460.797562  4356.915102   5381.266911   6789.774524   8589.054224   
True     8175.640146  9941.410203  11776.023847  13977.022880  16925.884987   

                 1977          1982          1987          1992          1997  \
wealthy                                                                         
False    10123.062167  10999.519354  11657.755578   9814.771634  11010.972268   
True     19039.312758  20896.041919  23564.659468  25343.621170  28294.849840   

                 2002          2007    mean_Z  
wealthy                                        
False    12762.305369  15908.649976 -0.559215  
True     31939.649055  35506.860676  0.639102

In [239]:
# Write output
data.to_csv("europe_normed.csv")

# Looping over data sets

In [243]:
# Import the data from files in a list
file_list = ["gapminder_gdp_africa.csv", "gapminder_gdp_asia.csv"]

for filename in file_list:
    data = pd.read_csv(filename, index_col = "country")
    print(filename)
    print(data.head(1))

gapminder_gdp_africa.csv
         gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                   
Algeria     2449.008185     3013.976023      2550.81688     3246.991771   

         gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                   
Algeria     4182.663766     4910.416756     5745.160213     5681.358539   

         gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                  
Algeria     5023.216647     4797.295051     5288.040382     6223.367465  
gapminder_gdp_asia.csv
             gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                       
Afghanistan      779.445314       820.85303       853.10071      836.197138   

             gdpPercap_1972  gdpPercap_1

In [245]:
# Automatically get a list of files. 
import glob

In [249]:
# Get all the csv files
glob.glob("*.csv")

['anscombe.csv',
 'europe_normed.csv',
 'gapminder_all.csv',
 'gapminder_gdp_africa.csv',
 'gapminder_gdp_americas.csv',
 'gapminder_gdp_asia.csv',
 'gapminder_gdp_europe.csv',
 'gapminder_gdp_oceania.csv',
 'iris.csv',
 'plots.csv',
 'species.csv',
 'surveys.csv']

In [251]:
#Get all the csv or tsv files
glob.glob("*.?sv")

['anscombe.csv',
 'europe_normed.csv',
 'gapminder_all.csv',
 'gapminder_gdp_africa.csv',
 'gapminder_gdp_americas.csv',
 'gapminder_gdp_asia.csv',
 'gapminder_gdp_europe.csv',
 'gapminder_gdp_oceania.csv',
 'iris.csv',
 'plots.csv',
 'species.csv',
 'surveys.csv']

In [255]:
# get a lis of all the continents
glob.glob("gapminder_gdp_*.csv")

['gapminder_gdp_africa.csv',
 'gapminder_gdp_americas.csv',
 'gapminder_gdp_asia.csv',
 'gapminder_gdp_europe.csv',
 'gapminder_gdp_oceania.csv']

In [261]:
# get continent- level data and aggregate into 1 data frame
data_frames = []

for filename in glob.glob("gapminder_gdp_*.csv"):
    print(filename)
    data = pd.read_csv(filename, index_col = "country")
    data_frames.append(data)

# Concatenate data frames
all_data = pd.concat(data_frames)


gapminder_gdp_africa.csv
gapminder_gdp_americas.csv
gapminder_gdp_asia.csv
gapminder_gdp_europe.csv
gapminder_gdp_oceania.csv


In [263]:
# Inspect our results
print(all_data.shape)
print(all_data.index)

(142, 13)
Index(['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       ...
       'Serbia', 'Slovak Republic', 'Slovenia', 'Spain', 'Sweden',
       'Switzerland', 'Turkey', 'United Kingdom', 'Australia', 'New Zealand'],
      dtype='object', name='country', length=142)


# Conditionals

In [266]:
# does a files end in "all.csv"?
for filename in glob.glob("gapminder*.csv"):
    print("Current file:", filename)
    print(filename.endswith("all.csv"))

Current file: gapminder_all.csv
True
Current file: gapminder_gdp_africa.csv
False
Current file: gapminder_gdp_americas.csv
False
Current file: gapminder_gdp_asia.csv
False
Current file: gapminder_gdp_europe.csv
False
Current file: gapminder_gdp_oceania.csv
False


In [268]:
# Get truth value of a statement
mass = 3

print(mass == 3)
print(mass>5)
print(mass<4)

True
False
True


In [270]:
# Test for membership in a collection
primes = [2, 3, 5]

print(2 in primes)
print(7 in primes)

True
False


In [272]:
# Test for missing values
df

1962         1967         1972
country                                           
Italy                NaN  10022.40131  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

In [274]:
# WHich values are missing?
df.isna()

1962   1967   1972
country                         
Italy         True  False  False
Montenegro    True   True   True
Netherlands  False  False  False
Norway       False  False  False
Poland        True   True   True

In [276]:
# are any values missing?
df.isna().any(axis = None)

True

In [280]:
# make choices with if- then statments
mass = 3.5 

if mass > 3.0:
    print(mass, "is large")

3.5 is large


In [282]:
# Test for files ending is "all.csv"
data_frames = []

for filenames in glob.glob("gapminder*.csv"):
    print(filename)
    if not filename.endswith("all.csv"):
        print("Passes test:", filename)
        data = pd.read_csv(filename, index_col = "country")
        data_frames.append(data)

all_data = pd.concat(data_frames)
print(all_data.shape)

gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_oceania.csv
gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_oceania.csv
gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_oceania.csv
gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_oceania.csv
gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_oceania.csv
gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_oceania.csv
(12, 12)


In [284]:
# Add an else condition
mass = 2.0

if mass > 3.0:
    print(mass, "is large")

else:
    print(mass,"is small")

2.0 is small


In [288]:
data_frames = []

for filename in glob.glob("gapminder*.csv"):
    if filename.endswith("all.csv"):
        print("not wanted")
    else:
        print("passes test", filename)
        data = pd.read_csv(filename, index_col = "country")
        data_frames.append(data)

all_data = pd.concat(data_frames)
print(all_data.shape)

not wanted
passes test gapminder_gdp_africa.csv
passes test gapminder_gdp_americas.csv
passes test gapminder_gdp_asia.csv
passes test gapminder_gdp_europe.csv
passes test gapminder_gdp_oceania.csv
(142, 13)


# challenge 1
1. Iterate through all the csv files in the directory
2. print the name and length ( number of rows) of any files less than 30 rows long

# challenge 2 
1. Iterate through all the CSV files in the directory
2. Print any filename that includes "europe", then print column names for that file.

In [300]:
for filename in glob.glob("*.csv"):
    data = pd.read_csv(filename)
    if data.shape[0] < 30:
        print(filename, data.shape[0])

anscombe.csv 11
gapminder_gdp_americas.csv 25
gapminder_gdp_oceania.csv 2
plots.csv 24


In [306]:
for filename in glob.glob("*.csv"):
    if "europe" in filename.lower():
        print(filename)
        data = pd.read_csv(filename)
        print(data.columns)

europe_normed.csv
Index(['country', '1952', '1957', '1962', '1967', '1972', '1977', '1982',
       '1987', '1992', '1997', '2002', '2007', 'mean_Z', 'wealthy'],
      dtype='object')
gapminder_gdp_europe.csv
Index(['country', 'gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962',
       'gdpPercap_1967', 'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982',
       'gdpPercap_1987', 'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002',
       'gdpPercap_2007'],
      dtype='object')


In [308]:
# You can specify additional tests with elif
mass = 3.5

if mass >9.0:
    print(mass, "is huge")
elif mass > 3.0:
    print(mass, "is large")
else: 
    print(mass,"is small")

3.5 is large


In [322]:
# You can do more complicated tests
mass = [1, 2, 3, 4, 5]
velocity = [5, 4, 3, 2, 5]

# get each pair of measurements
for m,v in zip(mass, velocity):
    if m <= 3 and v <= 3:
        print("small and slow")
    elif m <= 3 and v > 3:
        print("small and fast")
    elif m > 3 and v <= 3:
        print("large and slow")
    else:
        print("check data")

small and fast
small and fast
small and slow
large and slow
check data


# Functions

In [325]:
def print_greeting():
    print("Hello!")

In [327]:
print_greeting()

Hello!


In [335]:
# Functions take arguments
def print_date(year, month, day):
    joined_date = "/".join([str(year), str(month), str(day)])
    print(joined_date)

In [337]:
print_date ("1872","3","9")
print_date(1872,3,9)

1872/3/9
1872/3/9


In [343]:
# test your data inside your function
def average(values):
    """Return average of values or None if no values are supplied."""
    if len(values) == 0:
        return None
    else:
        return sum(values) / len(values)

In [345]:
a1 =average([1,2,3])
print(a1)

2.0


In [347]:
a2 = average([])
print(a2)

None


## challenge
write a function that encapsulates the z-score calculation. Your function should do the following:

1. read a csv file into a dataframe
2. calculate the mean z score for each item
3. calculate the mean z score for each country
4. append the mean z score as a new column
5. return the data frame

In [356]:
df = pd.read_csv("gapminder_gdp_africa.csv")

In [361]:
data = pd.read_csv("gapminder_gdp_africa.csv")

In [365]:
z =(data - data.mean(axis = None))/data.values.std(ddof=1)

In [375]:
mean_z = z.mean(axis=1)

In [371]:
data["mean_z"] = mean_z

In [403]:
def mean_z_score(filename, index_col=None):
    """Add a z score to a data frame"""
    
   # import data
    data = pd.read_csv(filename, index_col = index_col)

    #drop continent column if necessary.
    if "continent" in data.columns:
        data = data.drop("continent", axis=1)
    
    #calculate indivicual z-scores
    z =(data - data.values.mean()) / data.values.std()
    # Mean score for each country
    mean_z = z.mean(axis=1)

    #add to data frame
    data["mean_z"] = mean_z

    return data

In [381]:
pd.__version__

'2.2.2'

In [395]:
df = mean_z_score("gapminder_gdp_africa.csv", index_col = "country")

In [397]:
print(df.columns)

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007',
       'mean_z'],
      dtype='object')


# Putting it all together

In [400]:
# Get all the files we care abl=out and get total z-scores

In [405]:
data_frames = []

for filename in glob.glob("gapminder*.csv"):
    if not filename.endswith("all.csv"):
        df = mean_z_score(filename, index_col = "country")
        data_frames.append(df)

all_data = pd.concat(data_frames)

print(all_data.shape)
print(all_data.columns)
        

(142, 13)
Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007',
       'mean_z'],
      dtype='object')
